DROP TABLE IF EXISTS PRODUCT;
 
CREATE TABLE PRODUCT(
  PROD_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(16) NOT NULL,
  PRICE BIGINT NOT NULL
);

INSERT INTO PRODUCT (NAME, PRICE) VALUES ('TOASTER',1200);
INSERT INTO PRODUCT (NAME, PRICE) VALUES ('FRIDGE',120000);
INSERT INTO PRODUCT (NAME, PRICE) VALUES ('PAN',3000);
